### ISSUE TITLE
Panic when updating runner

### ISSUE THREAD

**Issue by stisti** [ohmu/tjob#1]
It seems it is not possible to update all runner attributes in one command:

To repro:

```
$ tjob runner add --url=$JENKINS_URL --user=tikksa --ssh-port=54410 --ssh-key=$HOME/id_dsa ub10
$ tjob list --remote
error: Get https://ultrabuilder10.f-secure.com/jenkins//view/All/api/json?tree=jobs[name]: x509: certificate signed by unknown authority
$ tjob runner add --url=$JENKINS_URL --user=tikksa --ssh-port=54410 --ssh-key=$HOME/id_dsa --insecure=true ub10
runner 'ub10' already exists, use the 'update' command
$ tjob runner update --url=$JENKINS_URL --user=tikksa --ssh-port=54410 --ssh-key=$HOME/id_dsa --insecure=true ub10
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x28 pc=0x5025]

goroutine 16 [running]:
runtime.panic(0x37a520, 0x5c9124)
    /usr/local/Cellar/go/1.3/libexec/src/pkg/runtime/panic.c:279 +0xf5
main.(*runnerUpdateCmd).Execute(0xc208002838, 0xc208050700, 0x0, 0x8, 0x0, 0x0)
    /Users/tikksa/go/src/github.com/ohmu/tjob/cmdrunner.go:92 +0x365
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc20803c300, 0xc20800e010, 0x8, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/tikksa/go/src/github.com/jessevdk/go-flags/parser.go:231 +0x657
main.main()
    /Users/tikksa/go/src/github.com/ohmu/tjob/main.go:65 +0x2f6

goroutine 19 [finalizer wait]:
runtime.park(0x25ef0, 0x5cc730, 0x5cb1e9)
    /usr/local/Cellar/go/1.3/libexec/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x5cc730, 0x5cb1e9)
    /usr/local/Cellar/go/1.3/libexec/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
    /usr/local/Cellar/go/1.3/libexec/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
    /usr/local/Cellar/go/1.3/libexec/src/pkg/runtime/proc.c:1445
```

However, updating a single attribute seems to work:

$ tjob runner update --insecure=true ub10

**Comment by melor** [comment]
thanks! fixed in 6fbc5f3e4f888b958fb0f118dabb10c1c7cad496
